TYPE_IN_URL = 'Введите ссылку на учебник: '
TYPE_IN_PDF_FILE_NAME = 'Введите имя PDF файла: '
ERROR = 'Ошибка!'
PARSING = 'Парсинг... Страница'
CREATING_PDF = 'Создание PDF...'
SUCCESS = 'Успешно!'
PRESS_ANY_KEY = 'Нажмите любую кнопку, чтобы закрыть программу.'